DEFAULT_PROMPT_I2V = "make this image come alive, cinematic motion, smooth animation"

DEFAULT_DURATION_SECONDS = 3.5
MIN_DURATION_SECONDS = 0.5
MAX_DURATION_SECONDS = 10.0

FPS_CHOICES = (16, 32, 64)

DEFAULT_INFERENCE_STEPS = 6
MIN_INFERENCE_STEPS = 1
MAX_INFERENCE_STEPS = 30

DEFAULT_VIDEO_QUALITY = 6
MIN_VIDEO_QUALITY = 1
MAX_VIDEO_QUALITY = 10
